# Generated by Django 3.2.23 on 2023-12-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231212_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contect',
            new_name='content',
        ),
    ]
